config/routes.rb
Rails.application.routes.draw do
  get 'user_roles/create'
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users

  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/new', to: 'restaurants#new'
  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurants'
  post 'restaurants', to: 'restaurants#create'
  patch 'restaurants/:id', to: 'restaurants#update'
  delete 'restaurants/:id', to: 'restaurants#destroy'
  
  get 'foods', to: 'foods#index'
  get 'foods/new', to: 'foods#new'
  get 'foods/:id', to: 'foods#show', as: 'food'
  get 'foods/:id/edit', to: 'foods#edit', as: 'edit_foods'
  post 'foods', to: 'foods#create'
  patch 'foods/:id', to: 'foods#update'
  delete 'foods/:id', to: 'foods#destroy'

  post 'home', to: 'user_roles#create', as: 'user_role'

  root "restaurants#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :restaurant

    has_one_attached :image

    validates :name, presence: true, length: { minimum: 4 }
    
    validates :price, presence: true, numericality: { only_float: true, greater_than: 0, less_than: 500 }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :foods, dependent: :destroy

    validates :name, presence: true, length: { minimum: 4 }

    validates :cuisine, presence: true, length: { minimum: 4 }

    def get_name
        return "#{name}"
    end

    def get_cuisine
        return "#{cuisine}"
    end 

    def name_cuisine
        return "#{name} (#{cuisine})"
    end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enum role: [:customer, :vendor, :admin]

  after_create :assign_default_role

  def assign_default_role
    add_role(:customer) if roles.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
            user_params.permit({ roles: [] }, :email, :password, :password_confirmation,)
        end
    end

    private     

    def forbidden
        flash[:alert] = "Unauthorized action."
        redirect_to root_path    
    end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_auth
  before_action :find_food, only: [:show, :update, :destroy, :edit]
  before_action :find_restaurant, only: [:new, :edit, :create, :update]

  def index
    @foods = Food.all
  end
  
  def show
  end

  def edit
  end

  def new
    @food = Food.new
  end

  def create    
    @food = Food.create(food_params)
    if @food.valid?
      redirect_to @food
    else
      flash.now[:alert] = @food.errors.full_messages.join('<br>').html_safe
      render 'new'
    end
  end

  def update
    begin
      @food.update!(food_params)
      redirect_to @food
    rescue
      flash.now[:alert] = @food.errors.full_messages.join('<br>').html_safe
      render 'edit'
    end
  end

  def destroy
    @food.image.purge
    @food.destroy
    redirect_to foods_path
  end

  private

  def check_auth
    authorize Food
  end
  
  def find_food
    @food = Food.find(params[:id])
  end

  def find_restaurant
    @restaurants = Restaurant.order(:get_name)
  end

  def food_params
    return params.require(:food).permit(:name, :description, :price, :restaurant_id, :image)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_auth
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :find_food, only: [:show, :edit, :update, :destroy]
  
  def home
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @foods.each do |food|
      @food = food
      return "#{@food.name}"
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(rest_params)
    if @restaurant.valid?
      redirect_to @restaurant
    else
      flash.now[:alert] = @restaurant.errors.full_messages.join('<br>').html_safe
      render 'new'
    end
  end

  def edit
  end

  def update
    begin
      @restaurant.update!(rest_params)
      redirect_to @restaurant
    rescue
      flash.now[:alert] = @restaurant.errors.full_messages.join('<br>').html_safe
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end
  
  private

  def check_auth
    authorize Restaurant
  end
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def find_food
    @foods = Restaurant.find(params[:id]).foods.all
  end

  def rest_params
    return params.require(:restaurant).permit(:name, :cuisine)
  end

end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController

  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
  
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  def create
    current_user.add_role :vendor
    redirect_to root_path
    flash[:alert] = "You're now registered as a Restaurant"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: @food, data: {turbo: false}) do |f| %>
  <fieldset class="mb-2">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :restaurant_id %>
    <%
        # collection_select takes 4 params:
        #   1. The attribute name in this model (book) to store the selected id in
        #   2. The collection from which to build the options
        #   3. The attribute in the collection items to use as the value of the option
        #   4. The attribute in the collection items to use as the caption of the option
    %>
    <%= f.collection_select :restaurant_id, @restaurants, :id, :get_name %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </fieldset>
  <fieldset class="py-2">
      <%= f.submit class: "button is-primary is-rounded" %>
  </fieldset>
<% end %>

app/views/foods/edit.html.erb
<h1 class="title is-2">Edit Food Item</h1>

<%= render 'form' %>

app/views/foods/index.html.erb
<h1 class="title is-1 is-italic">Speedy Feed's Selections!</h1>
<h1 class="title is-3">Meals:</h1>
<% @foods.each do |food| %>
    <p class="is-size-4"><%= link_to food.name, food %> by <%= link_to food.restaurant.get_name, food.restaurant %>, $<%= food.price %></p>
<% end %>

<div class="py-3">
    <%= user_signed_in? && policy(Food).new? ? link_to('Create Food Item', foods_new_path, class: "button is-primary is-outlined is-round") : '' %>
</div>

app/views/foods/new.html.erb
<h1 class="title is-3">New Menu Item</h1>

<%= render 'form' %>

app/views/foods/show.html.erb
<h1 class="title is-2"><%= @food.name %></h1>
<h1 class="subtitle is-3">by <%= @food.restaurant.name %></h1>
<h1 class="subtitle is-3"> $<%= @food.price %></h1>
<p><%= @food.description %></p>

<div class="my-3">
  <%= cl_image_tag(@food.image.key, crop: :scale, width: 250, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if @food.image.attached? %>
</div>

<div class="field is-grouped">
  <div class="mr-2">
    <%= user_signed_in? && policy(Food).new? ? link_to('Edit', edit_foods_path(@food), class: "button is-warning") : '' %>
  </div>
  <div class="mr-2">
    <%= user_signed_in? && policy(Food).new? ? button_to('Delete', @food, class: "button is-danger", method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete '#{@food.name}' as a food item?" } }) : '' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpeedyFeeds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand is-align-items-center">
        <a class="navbar-item">
          <%= link_to 'SF', root_path %>
        </a>

        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="true">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start is-align-items-center">
          <a class="navbar-item">
            <%= link_to 'Find Restaurants', restaurants_path %>
          </a>
          <a class="navbar-item">
            <%= link_to 'Search Meals', foods_path %>
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
            <% if user_signed_in? %>
              <a>
                <%= button_to 'Logout', destroy_user_session_path, class: 'button is-link', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out?" } } %>
              </a>
            <% else %>
              <a>
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-primary" %>
              </a>
              <a>
                <%= link_to 'Login', new_user_session_path, class: "button is-secondary" %>
              </a>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main class="mx-3">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: @restaurant, data: {turbo: false}) do |f| %>
    <fieldset class="mb-2">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </fieldset>
    <fieldset class="mb-2">
    <%= f.label :cuisine %>
    <%= f.text_field :cuisine %>
    <%
        # collection_select takes 4 params:
        # 1. the arrtribute name in this model (book) to store the selected id in
        # 2. The collection from which to build the options
        # 3. The attribute in the collection items to use as the value of the option
        # 4. The attribute in the collection items to use as the caption of the option
    %>
    <%# <%= f.collection_select :author_id, @authors, :id, :full_name %>
    <%# <%= f.number_field :author_id %> 
    </fieldset>
    <fieldset class="py-2">
        <%= f.submit class: "button is-primary is-rounded" %>
    </fieldset>
<% end %>

app/views/restaurants/edit.html.erb
<h3 class="title is-3">Restaurant information update form</h3>

<%= render 'form' %>

app/views/restaurants/home.html.erb
<h1 class="pb-3 title is-1 is-italic">Speedy Feeds</h1>

<h3 class="subtitle is-4">Welcome to Speedy Feeds! The food delivery service built by locals, for locals.</h3>

<% if current_user.has_any_role?(:vendor, :admin) %>
    <%= "" %>
<% else %>
    <p>Let's get started! You are currently registered as a customer. If you are looking to register your Restaurant as a Speedy Feeds vendor, click the button below:</p>
    <nav class="breadcrumb has-bullet-separator my-2" aria-label="breadcrumbs">
        <ul>
            <li><%= button_to 'Register Restaurant', user_role_path, class: 'button is-success is-large px-2', method: :post if policy(Restaurant).user_roles? %></li>
        </ul>
    </nav>
 <% end %>

app/views/restaurants/index.html.erb
<h1 class="title is-3">Restaurants in your area:</h1>
<% @restaurants.each do |restaurant| %>
    <h3 class="mr-2 title is-4"><%= link_to restaurant.get_name, restaurant %></h3>
    <h3 class="subtitle is-5"><%= restaurant.get_cuisine %></h3>
<% end %>



<div class="py-3">
    <%= user_signed_in? && policy(Restaurant).new? ? link_to('New Restaurant', restaurants_new_path, class: "button is-primary is-outlined is-round") : '' %>
</div>

app/views/restaurants/new.html.erb
<h1 class="title is-2">Restaurant Registration</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1 class="title is-2"><%= @restaurant.name %></h1>
<h1 class="subtitle is-3"><%= @restaurant.cuisine %></h1>

<div class="field is-grouped">
  <div class="mr-2">
    <%= user_signed_in? && policy(Restaurant).new? ? link_to('Edit', edit_restaurants_path(@restaurant), class: "button is-warning") : '' %>
  </div>
  <div class="mr-2">
    <%= user_signed_in? && policy(Restaurant).new? ? button_to('Delete', @restaurant, class: "button is-danger", method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete '#{@restaurant.name}' Restaurant?" } }) : '' %>
  </div>
</div>

<div class="my-5">
  <h3 class="title is-3 is-italic">Menu</h3>
  <% @foods.each do |food| %>
  <h3 class="title is-4"><%= food.name %> ... $<%= food.price %></h3>
  <h3 class="subtitle is-5"><%= food.description %></h3>
  <% end %>
</div>

<div class="py-3">
    <%= user_signed_in? && policy(Food).new? ? link_to('Create Food Item', foods_new_path, class: "button is-primary is-outlined is-round") : '' %>
</div>

app/views/user_roles/create.html.erb
<h1>UserRoles#create</h1>
<p>Find me in app/views/user_roles/create.html.erb</p>